apiVersion: eks.cattle.io/v1
kind: EKSClusterConfig
metadata:
  name: {{ .Values.clusterName }}
  namespace: cattle-global-data
  ownerReferences:
  - apiVersion: management.cattle.io/v3
    kind: Cluster
    name: {{ .Values.clusterName }}
spec:
  amazonCredentialSecret: {{ .Values.amazonCredentialSecret }}
  displayName: {{ .Values.clusterDisplayName | quote }}
  imported: false
  kmsKey: ""
  kubernetesVersion: {{ .Values.kubernetesVersion | quote }}
  loggingTypes: []
  nodeGroups:
  - desiredSize: {{ .Values.nodeGroupDesiredSize }}
    diskSize: 60
    ec2SshKey: ""
    gpu: false
    imageId: ""
    instanceType: {{ .Values.instanceType }}
    labels: {}
    launchTemplate: null
    maxSize: {{ .Values.nodeGroupMaxSize }}
    minSize: {{ .Values.nodeGroupMinSize }}
    nodegroupName: default
    requestSpotInstances: false
    resourceTags: {}
    spotInstanceTypes: []
    subnets: []
    tags: {}
    userData: ""
    version: {{ .Values.kubernetesVersion | quote }}
  privateAccess: {{ .Values.privateAccess }}
  publicAccess: {{ .Values.publicAccess }}
  publicAccessSources: []
  region: {{ .Values.region }}
  secretsEncryption: false
  securityGroups: []
  serviceRole: ""
  subnets: []
  tags: {}
