apiVersion: management.cattle.io/v3
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
spec:
  displayName: {{ .Values.clusterDisplayName | quote }}
  dockerRootDir: /var/lib/docker
  fleetWorkspaceName: fleet-default
  eksConfig:
    amazonCredentialSecret: cattle-global-data:cc-th64z
    displayName: {{ .Values.clusterDisplayName | quote }}
    kubernetesVersion: {{ .Values.kubernetesVersion }}
    nodeGroups:
    - nodegroupName: default
      instanceType: {{ .Values.instanceType }}
      minSize: {{ .Values.nodeGroupMinSize }}
      maxSize: {{ .Values.nodeGroupMaxSize }}
      desiredSize: {{ .Values.nodeGroupDesiredSize }}
      diskSize: 60
      version: {{ .Values.kubernetesVersion }}
    publicAccess: {{ .Values.publicAccess }}
    privateAccess: {{ .Values.privateAccess }}
    region: {{ .Values.region }}
