apiVersion: management.cattle.io/v3
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
spec:
  agentImageOverride: ""
  answers: {}
  description: ""
  desiredAgentImage: ""
  desiredAuthImage: ""
  displayName: {{ .Values.clusterDisplayName }}
  dockerRootDir: /var/lib/docker
  enableClusterAlerting: false
  enableClusterMonitoring: false
  enableNetworkPolicy: false
  fleetWorkspaceName: fleet-default
  gkeConfig:
    clusterAddons:
      horizontalPodAutoscaling: true
      httpLoadBalancing: true
    clusterIpv4Cidr: ""
    clusterName: {{ .Values.clusterDisplayName }}
    description: ""
    enableKubernetesAlpha: false
    googleCredentialSecret: {{ .Values.googleCredentialSecret }}
    imported: false
    ipAllocationPolicy:
      useIpAliases: true
    kubernetesVersion: {{ .Values.kubernetesVersion }}
    labels: {}
    locations: []
    loggingService: logging.googleapis.com/kubernetes
    maintenanceWindow: ""
    masterAuthorizedNetworks: {}
    monitoringService: monitoring.googleapis.com/kubernetes
    network: default
    networkPolicyEnabled: false
    nodePools:
    - autoscaling: {}
      config:
        diskSizeGb: 100
        diskType: pd-standard
        imageType: COS
        machineType: {{ .Values.machineType }}
        oauthScopes:
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
        - https://www.googleapis.com/auth/servicecontrol
        - https://www.googleapis.com/auth/service.management.readonly
        - https://www.googleapis.com/auth/trace.append
      initialNodeCount: {{ .Values.initialNodeCount }}
      management:
        autoRepair: true
        autoUpgrade: true
      maxPodsConstraint: 110
      name: default
      version: {{ .Values.kubernetesVersion }}
    privateClusterConfig: {}
    projectID: {{ .Values.googleProjectID }}
    region: ""
    subnetwork: default
    zone: {{ .Values.zone }}
  internal: false
  localClusterAuthEndpoint:
    enabled: false
  windowsPreferedCluster: false
